import { profile, about, expertise, career, projects, CATEGORIES, CATEGORY_FILTERS } from '../mockData.ts'
import type { Project, Category } from '../mockData.ts'

export { profile, about, expertise, career, projects, CATEGORIES, CATEGORY_FILTERS }
export type { Project, Category }

const extraProjects: Project[] = [
    {
        id: 'nexus-crm',
        title: 'Nexus CRM',
        category: 'Web Apps',
        year: '2025',
        tags: ['.NET', 'C#', 'PostgreSQL', 'React', 'Redis'],
        summary: 'CRM for service businesses: contacts, pipelines, activity timelines, and sales reporting.',
        demoUrl: 'https://example.com/demo/nexus',
        githubUrl: 'https://github.com/example/nexus-crm',
        detail: {
            overview: 'A CRM for service businesses that keeps contacts, opportunities, and activity history in one product with a reporting layer built for weekly reviews.',
            problem: 'Teams tracked customers in spreadsheets and scattered notes, so follow-ups fell through and pipeline visibility was guesswork.',
            solution: 'A web CRM with contact records, visual pipelines, an activity timeline per customer, and report exports for team reviews.',
            role: 'Backend design and build: data model, pipeline logic, and reporting queries. Owned the API the React client uses.',
            stack: ['.NET', 'C#', 'PostgreSQL', 'Redis', 'React', 'TypeScript', 'Docker'],
            architecture: ['Contacts and companies with activity timeline', 'Pipeline stages with weighted opportunities', 'Reporting service over time-boxed aggregates', 'Background jobs for export generation'],
            challenges: ['An activity timeline that stays fast as it grows', 'Pipeline rules simple enough for the whole team', 'Reporting that reflects the real funnel'],
            screenshots: [
                { label: 'Pipeline', caption: 'Opportunities through pipeline stages.' },
                { label: 'Timeline', caption: 'Customer activity history.' },
                { label: 'Report', caption: 'Weekly sales report export.' },
            ],
        },
    },
    {
        id: 'doc-vault',
        title: 'Doc Vault',
        category: 'Web Apps',
        year: '2024',
        tags: ['C#', '.NET', 'SQL Server', 'React'],
        summary: 'Document management system: versioning, permissions, audit trails, and full-text search.',
        githubUrl: 'https://github.com/example/doc-vault',
        detail: {
            overview: 'An internal document management system where every file has a version, an owner, an audit trail, and a permission set.',
            problem: 'Documents lived on shared drives with conflicting copies, no audit trail, and no way to find the current version.',
            solution: 'A web system with checked-in versions, folder permissions, full-text search, and a complete audit log.',
            role: 'Led backend design: storage model, permissions, and the audit pipeline.',
            stack: ['C#', '.NET', 'SQL Server', 'React', 'TypeScript'],
            architecture: ['Document store with immutable versions', 'Folder-based permission model', 'Full-text index over documents', 'Audit log written for every mutation'],
            challenges: ['Version storage without unbounded duplication', 'Permissions that stay enforceable at every read', 'Search across mixed file formats'],
            screenshots: [
                { label: 'Versions', caption: 'Version history for a document.' },
                { label: 'Search', caption: 'Full-text results across the vault.' },
            ],
        },
    },
    {
        id: 'kanban-flow',
        title: 'Kanban Flow',
        category: 'Web Apps',
        year: '2024',
        tags: ['TypeScript', 'Node.js', 'PostgreSQL', 'React'],
        summary: 'Workflow SaaS: custom boards, automation rules, and shared team views.',
        demoUrl: 'https://example.com/demo/kanban-flow',
        detail: {
            overview: 'A workflow SaaS where teams build their own boards with custom statuses, assign work, and automate repetitive moves.',
            problem: 'Teams used rigid tools that forced their process into preset lanes, so real work happened outside the tool.',
            solution: 'A flexible board system with custom statuses, automation rules, and shared views that reflect how the team actually works.',
            role: 'Backend services, automation engine, and the React frontend.',
            stack: ['TypeScript', 'Node.js', 'PostgreSQL', 'React', 'Redis'],
            architecture: ['Custom board and status definitions', 'Automation rule engine with event triggers', 'Real-time updates via Redis pub/sub', 'Shared team views with scoped access'],
            challenges: ['Automation rules that stay predictable', 'Real-time updates without conflicts', 'Custom statuses kept simple to configure'],
            screenshots: [
                { label: 'Board', caption: 'A team board with custom lanes.' },
                { label: 'Automation', caption: 'Rules that move cards automatically.' },
            ],
        },
    },
    {
        id: 'payroll-core',
        title: 'Payroll Core',
        category: 'Web Apps',
        year: '2023',
        tags: ['C#', '.NET', 'SQL Server', 'React'],
        summary: 'Private payroll and payment-calculation system for a services business.',
        detail: {
            overview: 'A private payroll system that calculates payments from time records, contract terms, and tax rules — no public demo, production only.',
            problem: 'Payroll was computed in spreadsheets each period, with manual checks and recurring calculation errors.',
            solution: 'A system with a period-based calculation engine, rule configuration, and an approval flow before payment.',
            role: 'Designed the calculation engine, rule model, and approval workflow.',
            stack: ['C#', '.NET', 'SQL Server', 'React'],
            architecture: ['Period-based calculation engine', 'Configurable pay rules per contract', 'Approval workflow with locked periods', 'Audit trail for every payment'],
            challenges: ['Calculation correctness that must be exact', 'Locked periods that forbid silent edits', 'A clear audit trail for finance review'],
            screenshots: [
                { label: 'Period', caption: 'A payroll period under calculation.' },
                { label: 'Rules', caption: 'Pay rules per contract.' },
            ],
        },
    },
    {
        id: 'quiz-arena-mini',
        title: 'Quiz Arena Mini',
        category: 'Telegram Mini Apps',
        year: '2025',
        tags: ['Telegram Mini App', 'React', 'Node.js', 'MongoDB'],
        summary: 'Live quiz rounds inside Telegram: questions, timers, and running scoreboards.',
        demoUrl: 'https://t.me/example/quizarena',
        detail: {
            overview: 'A Telegram Mini App that runs live quiz rounds: players join from the chat, answer timed questions, and watch the scoreboard move in real time.',
            problem: 'Communities ran quizzes in plain messages where scoring was manual and chaotic.',
            solution: 'A Mini App with joinable rounds, timed questions, real-time scores, and a moderator dashboard.',
            role: 'Full stack: round engine, scoring, and the Mini App UI.',
            stack: ['Telegram Mini App', 'React', 'Node.js', 'MongoDB', 'Telegram Bot API'],
            architecture: ['Round engine with timed questions', 'Real-time scoreboard via websockets', 'Question bank with categories', 'Moderator controls through the bot'],
            challenges: ['Timing fairness across network latency', 'Scoreboards that update without flicker', 'A lobby flow that works inside chat'],
            screenshots: [
                { label: 'Lobby', caption: 'Joining a round in chat.' },
                { label: 'Scoreboard', caption: 'Live standings mid-round.' },
            ],
        },
    },
    {
        id: 'moderator-bot',
        title: 'Moderator Bot',
        category: 'Telegram Bots',
        year: '2023',
        tags: ['TypeScript', 'Node.js', 'PostgreSQL'],
        summary: 'Community moderation: spam filtering, warnings, and graduated actions.',
        githubUrl: 'https://github.com/example/moderator-bot',
        detail: {
            overview: 'A moderation bot that filters spam, tracks warnings, and escalates actions for large community chats.',
            problem: 'Moderators manually reviewed every flagged message and repeated actions for the same members.',
            solution: 'A bot with automated filtering, a warning ledger, and graduated actions that escalate consistently.',
            role: 'Built the filtering pipeline, warning model, and action escalations.',
            stack: ['TypeScript', 'Node.js', 'PostgreSQL', 'Telegram Bot API'],
            architecture: ['Message filtering pipeline with rules', 'Warning ledger per member', 'Graduated action escalator', 'Moderator review queue'],
            challenges: ['False positives that frustrate members', 'Escalation rules that stay fair', 'Reviewing fast in high-traffic chats'],
            screenshots: [
                { label: 'Filter', caption: 'A flagged message in the queue.' },
                { label: 'Warnings', caption: 'Member warning ledger.' },
            ],
        },
    },
    {
        id: 'payout-bot',
        title: 'Payout Bot',
        category: 'Telegram Bots',
        year: '2023',
        tags: ['Python', 'Telegram Bot API', 'SQLite'],
        summary: 'Private payment notifications and payout ledger for a small business.',
        detail: {
            overview: 'A private bot that records payouts and sends payment notifications — production use, no public links.',
            problem: 'Payment confirmations arrived silently and records lived in a single notebook.',
            solution: 'A bot with a payout ledger, confirmation messages, and a monthly summary per contractor.',
            role: 'Designed the ledger model and notification flow.',
            stack: ['Python', 'Telegram Bot API', 'SQLite'],
            architecture: ['Payout ledger with immutable entries', 'Notification service for confirmations', 'Monthly summary generator'],
            challenges: ['Ledger integrity for finance records', 'Notifications that never duplicate', 'Running quietly without supervision'],
            screenshots: [
                { label: 'Ledger', caption: 'Recent payouts in the ledger.' },
                { label: 'Summary', caption: 'Monthly payout summary.' },
            ],
        },
    },
    {
        id: 'inventory-sync-bot',
        title: 'Inventory Sync Bot',
        category: 'Telegram Bots',
        year: '2022',
        tags: ['C#', 'Telegram Bot API', 'Redis'],
        summary: 'Stock sync and low-stock alerts pushed into channels.',
        detail: {
            overview: 'A private bot that watches stock changes and pushes low-stock alerts into operations channels.',
            problem: 'Stock levels were checked manually and restocking decisions lagged by days.',
            solution: 'A bot that subscribes to stock events and posts concise alerts when items fall below thresholds.',
            role: 'Built the event subscription, threshold logic, and alert formatting.',
            stack: ['C#', 'Telegram Bot API', 'Redis'],
            architecture: ['Stock event subscription', 'Threshold evaluation service', 'Alert formatter with deduplication', 'Channel routing config'],
            challenges: ['Alert storms during restocks', 'Thresholds configured per item group', 'Idempotent event handling'],
            screenshots: [
                { label: 'Alert', caption: 'A low-stock alert in the channel.' },
            ],
        },
    },
    {
        id: 'hex-rover',
        title: 'Hex Rover',
        category: 'Unity Games',
        year: '2024',
        tags: ['Unity', 'C#', 'Procedural Generation'],
        summary: 'Hex-grid exploration rover: procedural terrain, resources, and a scanner loop.',
        githubUrl: 'https://github.com/example/hex-rover',
        detail: {
            overview: 'A hex-grid exploration prototype where a rover scans procedural terrain, finds resources, and extends its route.',
            problem: 'A brief to prototype a satisfying scan-and-collect loop with replayable terrain.',
            solution: 'A hex-grid world with seeded generation, a scanner mechanic, and a route-planning layer.',
            role: 'Game systems: hex generation, scanning, and movement.',
            stack: ['Unity', 'C#', 'Procedural Generation'],
            architecture: ['Seeded hex terrain generation', 'Scanner mechanic with resource reveal', 'Route planning over discovered cells', 'Progression via collected resources'],
            challenges: ['Terrain variety from a seed', 'A scanning loop that stays rewarding', 'Stable performance across the grid'],
            screenshots: [
                { label: 'Explore', caption: 'The rover scanning new hexes.' },
                { label: 'Resources', caption: 'A revealed resource node.' },
            ],
        },
    },
    {
        id: 'glider-soar',
        title: 'Glider Soar',
        category: 'Unity Games',
        year: '2023',
        tags: ['Unity', 'C#'],
        summary: 'A glider flight prototype: wind currents, thermals, and distance scoring.',
        detail: {
            overview: 'A glider flight prototype where players ride wind currents and thermals to travel as far as possible.',
            problem: 'A prototype brief for a calm, skill-based flight loop without arcade controls.',
            solution: 'A physics-driven glider with an airflow system, thermals, and a distance-based scoring model.',
            role: 'Flight physics, airflow, and scoring systems.',
            stack: ['Unity', 'C#'],
            architecture: ['Glider flight model over physics', 'Airflow field with current and thermal zones', 'Distance scoring with altitude bonuses', 'Replayable level generation'],
            challenges: ['Glider feel that reads as calm', 'Thermals that reward skill', 'Frame rate on integrated GPUs'],
            screenshots: [
                { label: 'Flight', caption: 'Riding a thermal column.' },
                { label: 'Map', caption: 'Distance progress across the course.' },
            ],
        },
    },
]

export const round3Projects: Project[] = [...projects, ...extraProjects]